/**
 * Elysian Concierge & Elysian Weddings — Standard Reference & Demonstration Data
 * Grounded in luxury wedding coordination procedures by OVAimagination Events
 */

export const DEFAULT_EVENT_PROFILE = {
  id: 'evt_sample_01',
  name: 'Vanessa & Noah',
  eventType: 'wedding',
  partnerA: 'Vanessa Hayes',
  partnerB: 'Noah Sterling',
  weddingDate: '2027-07-15',
  ceremonyTime: '04:00 PM',
  receptionTime: '06:00 PM',
  timeZone: 'America/Los_Angeles',
  location: 'Malibu, CA',
  venue: 'The Grand Pavilion at Sunset Cove',
  guestCountTarget: 150,
  budget: 50000,
  theme: 'Champagne Gold & Midnight Navy',
  traditions: 'Modern Coastal & Classic Vows',
  planner: 'OVAimagination Events',
  serviceTier: 'Event Pass',
  isDemo: false,
};

export const MOCK_TASKS = [
  // 12+ Months Out
  { 
    id: 't1', 
    title: 'Determine budget ceiling and overall wedding aesthetic', 
    category: 'Planner', 
    period: '12+ Months', 
    completed: true, 
    dueDate: '2026-06-15', 
    notes: 'Agreed on Champagne Gold & Midnight Navy styling with $50k target.', 
    assignedTo: 'Both',
    statusTag: 'Completed',
    milestone: 'budget_set',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-06-15T14:30:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't2', 
    title: 'Draft guest list to get tentative head count', 
    category: 'Invitations', 
    period: '12+ Months', 
    completed: true, 
    dueDate: '2026-06-20', 
    notes: 'Initial head count target set at 150 guests.', 
    assignedTo: 'Both',
    statusTag: 'Completed',
    milestone: 'guestlist_drafted',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-06-20T11:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't3', 
    title: 'Research and book wedding venue (ceremony & reception)', 
    category: 'Venue', 
    period: '12+ Months', 
    completed: true, 
    dueDate: '2026-07-10', 
    notes: 'Booked The Grand Pavilion at Sunset Cove.', 
    assignedTo: 'Both',
    statusTag: 'Completed',
    milestone: 'venue_booked',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-07-10T16:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't4', 
    title: 'Retain professional wedding planner / coordinator', 
    category: 'Planner', 
    period: '12+ Months', 
    completed: true, 
    dueDate: '2026-07-20', 
    notes: 'Booked OVAimagination Events for full planning & styling.', 
    assignedTo: 'Both',
    statusTag: 'Completed',
    milestone: 'planner_booked',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-07-20T15:20:00Z',
    createdBy: 'user_01'
  },
  
  // 9 Months Out
  { 
    id: 't5', 
    title: 'Select wedding party and confirm bridesmaids & groomsmen', 
    category: 'Misc', 
    period: '9 Months', 
    completed: true, 
    dueDate: '2026-09-01', 
    notes: 'All bridesmaids and groomsmen confirmed!', 
    assignedTo: 'Both',
    statusTag: 'Completed',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-09-01T12:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't6', 
    title: 'Research and hire lead photographer & videographer', 
    category: 'Photography', 
    period: '9 Months', 
    completed: true, 
    dueDate: '2026-09-15', 
    notes: 'Booked Golden Hour Studios for full-day coverage.', 
    assignedTo: 'Bride',
    statusTag: 'Completed',
    milestone: 'photo_booked',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-09-15T18:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't7', 
    title: 'Shop for wedding attire, gown, and initial fittings', 
    category: 'Attire', 
    period: '9 Months', 
    completed: true, 
    dueDate: '2026-10-05', 
    notes: 'Attire ordered with Bellissima Bridal.', 
    assignedTo: 'Bride',
    statusTag: 'Completed',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-10-05T13:45:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't8', 
    title: 'Customize and publish Elysian wedding website & RSVP page', 
    category: 'Invitations', 
    period: '9 Months', 
    completed: true, 
    dueDate: '2026-10-20', 
    notes: 'Using The Timeless Arch template with live RSVP link.', 
    assignedTo: 'Groom',
    statusTag: 'Completed',
    milestone: 'website_published',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-10-20T17:00:00Z',
    createdBy: 'user_01'
  },
  
  // 6 Months Out
  { 
    id: 't9', 
    title: 'Finalize catering menu tasting and signature cocktails', 
    category: 'Catering', 
    period: '6 Months', 
    completed: false, 
    dueDate: '2027-01-15', 
    notes: 'Tasting scheduled with Culinaria Fine Dining.', 
    assignedTo: 'Both',
    statusTag: 'Waiting on Vendor',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't10', 
    title: 'Send formal digital save-the-dates and invitations', 
    category: 'Invitations', 
    period: '6 Months', 
    completed: true, 
    dueDate: '2027-01-20', 
    notes: 'Save-the-dates and digital invites dispatched to guests.', 
    assignedTo: 'Bride',
    statusTag: 'Completed',
    milestone: 'invites_sent',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2027-01-20T09:30:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't11', 
    title: 'Hire floral designer and approve centerpiece mockups', 
    category: 'Florals', 
    period: '6 Months', 
    completed: false, 
    dueDate: '2027-02-05', 
    notes: 'Reviewing proposal from Elysian Atelier Florals.', 
    assignedTo: 'Bride',
    statusTag: 'Waiting on Partner',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't12', 
    title: 'Book ceremony musicians and reception DJ', 
    category: 'Music', 
    period: '6 Months', 
    completed: true, 
    dueDate: '2027-02-15', 
    notes: 'DJ Luminary confirmed for reception.', 
    assignedTo: 'Groom',
    statusTag: 'Completed',
    milestone: 'music_booked',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2027-02-15T11:15:00Z',
    createdBy: 'user_01'
  },
  
  // 3 Months Out
  { 
    id: 't13', 
    title: 'Order wedding cake and groom dessert table', 
    category: 'Bakery', 
    period: '3 Months', 
    completed: false, 
    dueDate: '2027-04-10', 
    notes: 'Need to finalize flavors with Sweet Artistry Confections.', 
    assignedTo: 'Bride',
    statusTag: 'In Progress',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't14', 
    title: 'Purchase wedding bands and arrange custom engraving', 
    category: 'Rings', 
    period: '3 Months', 
    completed: false, 
    dueDate: '2027-04-15', 
    notes: 'Ring sizing and engraving date scheduled.', 
    assignedTo: 'Both',
    statusTag: 'In Progress',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't15', 
    title: 'Track RSVP deadline and follow up on pending guests', 
    category: 'Invitations', 
    period: '3 Months', 
    completed: false, 
    dueDate: '2027-04-20', 
    notes: 'RSVP deadline set for 4 weeks before event date.', 
    assignedTo: 'Bride',
    statusTag: 'In Progress',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't16', 
    title: 'Schedule hair and bridal makeup trials', 
    category: 'Hair & Makeup', 
    period: '3 Months', 
    completed: false, 
    dueDate: '2027-05-01', 
    notes: 'Trial booked with Elysian Glamour Studio.', 
    assignedTo: 'Bride',
    statusTag: 'In Progress',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  
  // 1 Month Out
  { 
    id: 't17', 
    title: 'Apply for marriage license at county clerk office', 
    category: 'Misc', 
    period: '1 Month', 
    completed: false, 
    dueDate: '2027-06-15', 
    notes: 'Must go to county registrar with photo IDs within 90 days of ceremony.', 
    assignedTo: 'Both',
    statusTag: 'Waiting on Partner',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't18', 
    title: 'Finalize table seating chart and floor plan', 
    category: 'Decor', 
    period: '1 Month', 
    completed: false, 
    dueDate: '2027-06-20', 
    notes: 'Assign guests to tables once remaining RSVPs arrive.', 
    assignedTo: 'Both',
    statusTag: 'In Progress',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't19', 
    title: 'Submit finalized guest head count to venue & caterer', 
    category: 'Catering', 
    period: '1 Month', 
    completed: false, 
    dueDate: '2027-06-25', 
    notes: 'Culinaria Fine Dining requires final count 14 days before ceremony.', 
    assignedTo: 'Planner',
    statusTag: 'Waiting on Planner',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't20', 
    title: 'Write personal wedding vows and practice toasts', 
    category: 'Officiant', 
    period: '1 Month', 
    completed: false, 
    dueDate: '2027-07-01', 
    notes: 'Draft assisted by Elysian AI Vow Assistant.', 
    assignedTo: 'Both',
    statusTag: 'In Progress',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  
  // Day-Of
  { 
    id: 't21', 
    title: 'Entrust wedding rings and marriage license to Best Man', 
    category: 'Rings', 
    period: 'Day-Of', 
    completed: false, 
    dueDate: '2027-07-15', 
    notes: 'Ensure documents and rings are in safe custody before ceremony.', 
    assignedTo: 'Groom',
    statusTag: 'Scheduled',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't22', 
    title: 'Enjoy bridal suite breakfast and stay hydrated', 
    category: 'Misc', 
    period: 'Day-Of', 
    completed: false, 
    dueDate: '2027-07-15', 
    notes: 'Caterer delivery scheduled for 08:30 AM.', 
    assignedTo: 'Both',
    statusTag: 'Scheduled',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
  { 
    id: 't23', 
    title: 'Relax, celebrate, and embrace your wedding day!', 
    category: 'Misc', 
    period: 'Day-Of', 
    completed: false, 
    dueDate: '2027-07-15', 
    notes: 'You made it! Trust your OVAimagination coordinator and cherish every moment.', 
    assignedTo: 'Both',
    statusTag: 'Scheduled',
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
    createdBy: 'user_01'
  },
];

export const MOCK_VENDORS = [
  {
    id: 'v1',
    name: 'OVAimagination Events',
    category: 'Planner',
    rating: 4.9,
    reviewsCount: 48,
    costRange: '$$$',
    location: 'Los Angeles, CA',
    status: 'Booked',
    contactName: 'Olivia Vance',
    email: 'olivia@ovaimagination.com',
    phone: '(555) 019-2834',
    website: 'https://ovaimagination.com',
    contractPrice: 4500,
    paidAmount: 2250,
    nextPaymentDate: '2027-06-01',
    notes: 'Official planning partner for Elysian Concierge. Oversees full styling and day-of orchestration.',
  },
  {
    id: 'v2',
    name: 'The Grand Pavilion at Sunset Cove',
    category: 'Venue',
    rating: 4.8,
    reviewsCount: 112,
    costRange: '$$$$',
    location: 'Malibu, CA',
    status: 'Booked',
    contactName: 'Marcus Sterling',
    email: 'events@grandpavilion.com',
    phone: '(555) 014-9831',
    website: 'https://grandpavilion.com',
    contractPrice: 18000,
    paidAmount: 9000,
    nextPaymentDate: '2027-05-15',
    notes: 'Ocean-view outdoor lawn ceremony space and luxury gold ballroom for reception.',
  },
  {
    id: 'v3',
    name: 'Golden Hour Studios',
    category: 'Photography',
    rating: 4.9,
    reviewsCount: 64,
    costRange: '$$$',
    location: 'Pasadena, CA',
    status: 'Booked',
    contactName: 'Chloe Bennett',
    email: 'chloe@goldenhourstudios.com',
    phone: '(555) 018-7241',
    website: 'https://goldenhourstudios.com',
    contractPrice: 3800,
    paidAmount: 1900,
    nextPaymentDate: '2027-07-01',
    notes: 'Full-day coverage, includes engagement shoot and second shooter.',
  },
  {
    id: 'v4',
    name: 'Culinaria Fine Dining',
    category: 'Catering',
    rating: 4.7,
    reviewsCount: 89,
    costRange: '$$$',
    location: 'Santa Monica, CA',
    status: 'Shortlisted',
    contactName: 'Chef Andre',
    email: 'info@culinariafine.com',
    phone: '(555) 013-6490',
    website: 'https://culinariafine.com',
    contractPrice: 9500,
    paidAmount: 0,
    nextPaymentDate: null,
    notes: 'Custom plating options. Sample tasting includes herb-crusted filet mignon and lavender halibut.',
  },
  {
    id: 'v5',
    name: 'DJ Luminary Entertainment',
    category: 'Music',
    rating: 5.0,
    reviewsCount: 73,
    costRange: '$$',
    location: 'Los Angeles, CA',
    status: 'Booked',
    contactName: 'Dave Miller',
    email: 'dave@djluminary.com',
    phone: '(555) 016-5287',
    website: 'https://djluminary.com',
    contractPrice: 2200,
    paidAmount: 1100,
    nextPaymentDate: '2027-07-15',
    notes: 'Includes wireless microphones, custom warm amber uplighting, and sound coordination.',
  },
  {
    id: 'v6',
    name: 'Elysian Atelier Florals',
    category: 'Florals',
    rating: 4.8,
    reviewsCount: 37,
    costRange: '$$$',
    location: 'Beverly Hills, CA',
    status: 'Shortlisted',
    contactName: 'Elena Rostova',
    email: 'elena@elysianflorals.com',
    phone: '(555) 011-8843',
    website: 'https://elysianflorals.com',
    contractPrice: 5000,
    paidAmount: 0,
    nextPaymentDate: null,
    notes: 'Proposing white roses, champagne eucalyptus accents, and tall candelabra centerpieces.',
  },
  {
    id: 'v7',
    name: 'Bellissima Bridal Couture',
    category: 'Attire',
    rating: 4.6,
    reviewsCount: 154,
    costRange: '$$$',
    location: 'Los Angeles, CA',
    status: 'Booked',
    contactName: 'Sarah Jenkins',
    email: 'fittings@bellissimabridal.com',
    phone: '(555) 012-9051',
    website: 'https://bellissimabridal.com',
    contractPrice: 3200,
    paidAmount: 3200,
    nextPaymentDate: null,
    notes: 'Wedding gown ordered with custom veil. Second fitting scheduled for June 1st.',
  },
];

export const MOCK_GUESTS = [
  // Bride's Family
  { id: 'g1', name: 'Eleanor Johnson', group: "Bride's Family", email: 'eleanor.j@example.com', phone: '(555) 019-1122', status: 'Attending', rsvpReceived: true, meal: 'Beef', table: 1, plusOnes: 0, notes: 'Mother of the Bride.' },
  { id: 'g2', name: 'Robert Johnson', group: "Bride's Family", email: 'robert.j@example.com', phone: '(555) 019-1123', status: 'Attending', rsvpReceived: true, meal: 'Beef', table: 1, plusOnes: 0, notes: 'Father of the Bride.' },
  { id: 'g3', name: 'Thomas Johnson', group: "Bride's Family", email: 'tom.j@example.com', phone: '(555) 019-5566', status: 'Attending', rsvpReceived: true, meal: 'Vegetarian', table: 3, plusOnes: 1, notes: "Bride's brother." },
  { id: 'g4', name: 'Emily Johnson', group: "Bride's Family", email: 'emily.j@example.com', phone: '(555) 019-5567', status: 'Attending', rsvpReceived: true, meal: 'Chicken', table: 3, plusOnes: 0, notes: 'Thomas Johnson companion.' },
  
  // Groom's Family
  { id: 'g5', name: 'Arthur Sterling', group: "Groom's Family", email: 'arthur.s@example.com', phone: '(555) 015-4422', status: 'Attending', rsvpReceived: true, meal: 'Fish', table: 2, plusOnes: 0, notes: 'Father of the Groom.' },
  { id: 'g6', name: 'Grace Sterling', group: "Groom's Family", email: 'grace.s@example.com', phone: '(555) 015-4423', status: 'Attending', rsvpReceived: true, meal: 'Fish', table: 2, plusOnes: 0, notes: 'Mother of the Groom.' },
  { id: 'g7', name: 'Lucy Sterling', group: "Groom's Family", email: 'lucy.s@example.com', phone: '(555) 015-9988', status: 'Attending', rsvpReceived: true, meal: 'Vegetarian', table: 4, plusOnes: 0, notes: "Groom's sister (Bridesmaid)." },

  // Friends & Wedding Party
  { id: 'g8', name: 'David Smith', group: 'Friends', email: 'dsmith@example.com', phone: '(555) 012-3344', status: 'Attending', rsvpReceived: true, meal: 'Beef', table: 5, plusOnes: 1, notes: 'Best Man.' },
  { id: 'g9', name: 'Jessica Smith', group: 'Friends', email: 'jess.smith@example.com', phone: '(555) 012-3345', status: 'Attending', rsvpReceived: true, meal: 'Chicken', table: 5, plusOnes: 0, notes: 'David Smith companion.' },
  { id: 'g10', name: 'Michael Chang', group: 'Friends', email: 'mchang@example.com', phone: '(555) 017-6655', status: 'Attending', rsvpReceived: true, meal: 'Beef', table: 5, plusOnes: 0, notes: 'Groomsman.' },
  { id: 'g11', name: 'Sophia Martinez', group: 'Friends', email: 'sophia.m@example.com', phone: '(555) 013-4411', status: 'Pending', rsvpReceived: false, meal: 'Pending', table: 0, plusOnes: 0, notes: 'Maid of Honor.' },
  { id: 'g12', name: 'Daniel Kim', group: 'Friends', email: 'dkim@example.com', phone: '(555) 014-8877', status: 'Pending', rsvpReceived: false, meal: 'Pending', table: 0, plusOnes: 1, notes: 'College friend.' },
  { id: 'g13', name: 'Rachel Green', group: 'Friends', email: 'rachel@example.com', phone: '(555) 016-1212', status: 'Declined', rsvpReceived: true, meal: 'Declined', table: 0, plusOnes: 0, notes: 'Traveling out of the country.' },
  { id: 'g14', name: 'Monica Geller', group: 'Friends', email: 'monica@example.com', phone: '(555) 016-1313', status: 'Attending', rsvpReceived: true, meal: 'Beef', table: 6, plusOnes: 0, notes: 'Close family friend.' },
  { id: 'g15', name: 'Chandler Bing', group: 'Friends', email: 'chandler@example.com', phone: '(555) 016-1414', status: 'Attending', rsvpReceived: true, meal: 'Chicken', table: 6, plusOnes: 0, notes: "Monica's husband." },
];

export const MOCK_BUDGET = {
  total: 50000,
  categories: [
    { name: 'Venue', planned: 18000, contracted: 18000, color: '#6366f1' },
    { name: 'Catering', planned: 10000, contracted: 9500, color: '#f59e0b' },
    { name: 'Planner', planned: 5000, contracted: 4500, color: '#d4af37' },
    { name: 'Photography', planned: 4000, contracted: 3800, color: '#ec4899' },
    { name: 'Florals', planned: 5000, contracted: 5000, color: '#10b981' },
    { name: 'Music', planned: 2500, contracted: 2200, color: '#3b82f6' },
    { name: 'Attire', planned: 4000, contracted: 3200, color: '#f472b6' },
    { name: 'Misc', planned: 1500, contracted: 800, color: '#94a3b8' },
  ],
  payments: [
    { id: 'p1', vendorName: 'The Grand Pavilion at Sunset Cove', category: 'Venue', amount: 9000, date: '2026-07-15', status: 'Paid', method: 'Wire Transfer', notes: 'Initial venue reservation deposit (50%)' },
    { id: 'p2', vendorName: 'OVAimagination Events', category: 'Planner', amount: 2250, date: '2026-07-25', status: 'Paid', method: 'Credit Card', notes: 'Retainer deposit for wedding planning services' },
    { id: 'p3', vendorName: 'Golden Hour Studios', category: 'Photography', amount: 1900, date: '2026-09-20', status: 'Paid', method: 'Check', notes: 'Half-down booking deposit for photo coverage' },
    { id: 'p4', vendorName: 'Bellissima Bridal Couture', category: 'Attire', amount: 3200, date: '2026-10-10', status: 'Paid', method: 'Credit Card', notes: 'Full bridal gown and custom veil balance paid' },
    { id: 'p5', vendorName: 'DJ Luminary Entertainment', category: 'Music', amount: 1100, date: '2027-02-20', status: 'Paid', method: 'Electronic Transfer', notes: 'DJ Luminary booking retainer' },
    { id: 'p6', vendorName: 'The Grand Pavilion at Sunset Cove', category: 'Venue', amount: 9000, date: '2027-05-15', status: 'Upcoming', method: 'Wire Transfer', notes: 'Final venue balance due 60 days before event' },
    { id: 'p7', vendorName: 'OVAimagination Events', category: 'Planner', amount: 2250, date: '2027-06-01', status: 'Upcoming', method: 'Credit Card', notes: 'Final coordinator installment' },
  ],
};

export const MOCK_TIMELINE = [
  { id: 'tl1', time: '08:00 AM', title: 'Hair and Makeup Styling Starts', location: 'Bridal Suite', desc: 'Bridesmaids and mother of the bride first. Bride glam commences at 09:30 AM.', status: 'Completed', assignee: 'Bride' },
  { id: 'tl2', time: '10:00 AM', title: 'Groomsmen Dressing & Detail Shots', location: 'Groom Suite', desc: 'Groom and groomsmen dress. Photographer captures cufflinks, shoes, and rings.', status: 'Pending', assignee: 'Groom' },
  { id: 'tl3', time: '12:30 PM', title: 'Private First Look & Couple Portraits', location: 'Pavilion Botanical Garden', desc: 'Intimate first look reveal. Lead photographer and videographer film couple session.', status: 'Pending', assignee: 'Both' },
  { id: 'tl4', time: '01:30 PM', title: 'Wedding Party & Family Formals', location: 'Pavilion Botanical Garden', desc: 'Shoot immediate family, bridesmaids, and groomsmen groupings.', status: 'Pending', assignee: 'Both' },
  { id: 'tl5', time: '03:30 PM', title: 'Guest Arrival & Welcome Music', location: 'Sunset Lawn', desc: 'Ushers guide guests to seating. Acoustic pre-ceremony strings commence.', status: 'Pending', assignee: 'Planner' },
  { id: 'tl6', time: '04:00 PM', title: 'Wedding Ceremony', location: 'Sunset Lawn', desc: 'Processional begins. Personal vows and ring exchange. Recessional at 04:35 PM.', status: 'Pending', assignee: 'Both' },
  { id: 'tl7', time: '04:40 PM', title: 'Cocktail Hour & Golden Hour Sunset Photos', location: 'Ocean View Terrace', desc: 'Guests enjoy artisanal hors d\'oeuvres and champagne. Couple shoots sunset portraits.', status: 'Pending', assignee: 'Both' },
  { id: 'tl8', time: '05:45 PM', title: 'Grand Reception Ballroom Entrance', location: 'Gold Grand Ballroom', desc: 'Guests seated. Grand entrance of couple followed immediately by First Dance.', status: 'Pending', assignee: 'Both' },
  { id: 'tl9', time: '06:00 PM', title: 'Dinner Service & Speeches', location: 'Gold Grand Ballroom', desc: 'Plated dinner served. Maid of Honor, Best Man, and parents deliver toasts.', status: 'Pending', assignee: 'Both' },
  { id: 'tl10', time: '08:00 PM', title: 'Cake Cutting & Dance Floor Celebration', location: 'Gold Grand Ballroom', desc: 'Cake cutting followed by parent dances. DJ Luminary opens dance floor.', status: 'Pending', assignee: 'Both' },
  { id: 'tl11', time: '11:00 PM', title: 'Grand Sparkler Send-Off', location: 'Front Portico', desc: 'Guests line the pathway with gold sparklers for the couple’s grand farewell.', status: 'Pending', assignee: 'Planner' },
];

export const MOCK_MISSIONS = [
  {
    id: 'm1',
    title: 'Finalize Catering Menu Selections',
    category: 'Catering',
    reward: '+5 AI Credits',
    urgency: 'This Week',
    description: 'Review the two plating options from Culinaria Fine Dining and confirm dietary choices.',
    actionUrl: '/vendors',
    completed: false,
    snoozed: false
  },
  {
    id: 'm2',
    title: 'Follow Up with 3 Pending RSVPs',
    category: 'Guests',
    reward: '+5 AI Credits',
    urgency: 'Medium',
    description: 'Send quick friendly reminders to unconfirmed friends so table seating can be finalized.',
    actionUrl: '/guests',
    completed: false,
    snoozed: false
  },
  {
    id: 'm3',
    title: 'Draft Personal Wedding Vows',
    category: 'Officiant',
    reward: '+10 AI Credits',
    urgency: 'Recommended',
    description: 'Use the Elysian AI Vow Assistant to write your initial promises and memories draft.',
    actionUrl: '/ai-chat',
    completed: false,
    snoozed: false
  }
];

export const MOCK_AUDIT_LOG = [
  { id: 'aud_1', action: 'Central Profile Synchronized', user: 'Vanessa & Noah', timestamp: '2026-10-04T18:00:00Z', details: 'Wedding date set to July 15, 2027 in Malibu, CA' },
  { id: 'aud_2', action: 'Budget Ceiling Adjusted', user: 'Vanessa & Noah', timestamp: '2026-10-04T18:05:00Z', details: 'Ceiling set to $50,000 USD' },
  { id: 'aud_3', action: 'Vendor Contract Logged', user: 'Vanessa & Noah', timestamp: '2026-10-04T18:10:00Z', details: 'The Grand Pavilion booked for $18,000' },
  { id: 'aud_4', action: 'Digital Invitation Published', user: 'Vanessa & Noah', timestamp: '2026-10-04T18:15:00Z', details: 'The Timeless Arch template live at unique URL' },
];
