'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useWeddingStore } from '@/lib/store';
import { formatDate, daysUntil, calculateProgress, getCategoryColor, getCategoryIcon } from '@/lib/utils';

export default function ChecklistPage() {
  const router = useRouter();
  const store = useWeddingStore();
  const { user, tasks, loading, addTask, updateTask, deleteTask } = store;

  const [activeFilter, setActiveFilter] = useState('all'); // all, month, upcoming, completed
  const [modalOpen, setModalOpen] = useState(false);
  const [expandedTaskId, setExpandedTaskId] = useState(null);
  const [newTask, setNewTask] = useState({
    title: '',
    category: 'Planner',
    dueDate: '',
    notes: '',
    assignedTo: 'Both',
  });

  useEffect(() => {
    if (!loading && !user) {
      router.push('/auth');
    }
  }, [user, loading, router]);

  if (loading || !user) {
    return (
      <div className="flex-center" style={{ minHeight: '100vh', background: '#0d0d1a' }}>
        <div style={{ width: '40px', height: '40px', border: '3px solid rgba(201, 169, 110, 0.15)', borderTopColor: '#c9a96e', borderRadius: '50%', animation: 'spin 1s linear infinite' }}></div>
        <style jsx>{`
          @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
          .flex-center { display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; background: #0d0d1a; }
        `}</style>
      </div>
    );
  }

  // Calculate statistics
  const totalCount = tasks.length;
  const completedCount = tasks.filter(t => t.completed).length;
  const progress = calculateProgress(completedCount, totalCount);

  // Filters logic
  const filteredTasks = tasks.filter(task => {
    if (activeFilter === 'completed') return task.completed;
    if (task.completed && activeFilter !== 'all') return false; // don't show completed in "this month" or "upcoming"
    
    if (activeFilter === 'month') {
      const days = daysUntil(task.dueDate);
      return days >= 0 && days <= 30;
    }
    if (activeFilter === 'upcoming') {
      const days = daysUntil(task.dueDate);
      return days > 30;
    }
    return true;
  });

  // Sort tasks by due date
  const sortedTasks = [...filteredTasks].sort((a, b) => new Date(a.dueDate) - new Date(b.dueDate));

  const handleToggleTask = (id, currentVal) => {
    updateTask(id, { completed: !currentVal });
  };

  const handleTaskSubmit = (e) => {
    e.preventDefault();
    if (!newTask.title || !newTask.dueDate) return;

    const daysLeft = daysUntil(newTask.dueDate);
    let period = 'Upcoming';
    if (daysLeft < 0) period = 'Overdue';
    else if (daysLeft <= 30) period = 'This Month';
    else if (daysLeft > 365) period = '12+ Months';
    else if (daysLeft > 180) period = '9 Months';
    else if (daysLeft > 90) period = '6 Months';
    else period = '3 Months';

    addTask({
      ...newTask,
      period,
    });

    setNewTask({
      title: '',
      category: 'Planner',
      dueDate: '',
      notes: '',
      assignedTo: 'Both',
    });
    setModalOpen(false);
  };

  const handleDeleteTask = (id) => {
    if (confirm('Are you sure you want to delete this task?')) {
      deleteTask(id);
    }
  };

  return (
    <main className="checklist-layout">
      <div className="navbar-spacer"></div>

      <div className="container py-8 max-w-4xl">
        {/* Checklist Header */}
        <div className="flex-between mb-6 flex-wrap gap-4">
          <div>
            <h1 className="h2 font-heading text-gold mb-1">Wedding Checklist</h1>
            <p className="body-sm text-secondary">
              Track your timeline and milestones. Standard template generated by **OVAimagination Events**.
            </p>
          </div>
          <button 
            onClick={() => setModalOpen(true)}
            className="btn btn-primary"
          >
            ＋ Add Custom Task
          </button>
        </div>

        {/* Progress Bar */}
        <div className="card glass-panel p-6 mb-6">
          <div className="flex-between mb-2">
            <span className="body-sm text-primary font-bold">Overall Progress</span>
            <span className="body-sm text-gold font-bold">{progress}% completed ({completedCount}/{totalCount})</span>
          </div>
          <div className="progress-bar-bg w-full">
            <div className="progress-bar-fill" style={{ width: `${progress}%` }}></div>
          </div>
        </div>

        {/* Filter Tabs */}
        <div className="tabs mb-6 flex bg-secondary p-1 rounded-lg border border-divider">
          {[
            { id: 'all', label: '📂 All Tasks' },
            { id: 'month', label: '⏰ This Month' },
            { id: 'upcoming', label: '📅 Upcoming' },
            { id: 'completed', label: '✓ Completed' }
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveFilter(tab.id)}
              className={`tab flex-1 py-3 px-4 text-center text-sm font-bold rounded-md transition cursor-pointer ${
                activeFilter === tab.id ? 'bg-gold text-dark' : 'text-muted hover:text-primary'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Tasks List */}
        <div className="tasks-list-container flex-col gap-4">
          {sortedTasks.length > 0 ? (
            sortedTasks.map(task => {
              const isOverdue = daysUntil(task.dueDate) < 0 && !task.completed;
              const isExpanded = expandedTaskId === task.id;
              
              return (
                <div 
                  key={task.id} 
                  className={`card glass-panel task-card-item transition ${task.completed ? 'task-completed-style' : ''} ${
                    isOverdue ? 'task-overdue-style' : ''
                  }`}
                >
                  <div className="flex-between p-4 items-center">
                    <div className="flex-start items-center gap-3 flex-1">
                      <input 
                        type="checkbox" 
                        checked={task.completed}
                        onChange={() => handleToggleTask(task.id, task.completed)}
                        className="task-checkbox"
                      />
                      <div className="flex-col">
                        <span 
                          onClick={() => setExpandedTaskId(isExpanded ? null : task.id)}
                          className={`task-title text-primary font-bold body-sm cursor-pointer hover:text-gold ${
                            task.completed ? 'line-through text-muted' : ''
                          }`}
                        >
                          {task.title}
                        </span>
                        
                        <div className="flex-start gap-2 items-center mt-1 flex-wrap">
                          <span 
                            className="category-dot" 
                            style={{ backgroundColor: getCategoryColor(task.category) }}
                          ></span>
                          <span className="text-xs text-muted">
                            {getCategoryIcon(task.category)} {task.category}
                          </span>
                          <span className="text-xs text-muted">•</span>
                          <span className={`text-xs ${isOverdue ? 'text-danger font-bold animate-pulse' : 'text-muted'}`}>
                            {isOverdue ? `⚠️ Overdue (${formatDate(task.dueDate)})` : `Due: ${formatDate(task.dueDate)}`}
                          </span>
                          <span className="text-xs text-muted">•</span>
                          <span className="text-xs text-muted">Assignee: {task.assignedTo || 'Both'}</span>
                        </div>
                      </div>
                    </div>
                    
                    <div className="flex-start items-center gap-2">
                      <button 
                        onClick={() => setExpandedTaskId(isExpanded ? null : task.id)}
                        className="btn btn-ghost btn-sm text-secondary"
                      >
                        {isExpanded ? '▲ Details' : '▼ Details'}
                      </button>
                      <button 
                        onClick={() => handleDeleteTask(task.id)}
                        className="btn btn-ghost btn-sm text-danger"
                      >
                        🗑️
                      </button>
                    </div>
                  </div>

                  {/* Expanded Task Notes */}
                  {isExpanded && (
                    <div className="task-notes-expanded p-4 border-t bg-secondary-opaque">
                      <h4 className="overline mb-2">Planning Notes</h4>
                      <p className="body-sm text-secondary mb-2 whitespace-pre-line">
                        {task.notes || 'No detailed guidelines. Ask your Elysian AI concierge for tips on this task!'}
                      </p>
                      <div className="flex justify-end mt-4">
                        <Link 
                          href={`/ai-chat?q=${encodeURIComponent(`advice for ${task.title}`)}`}
                          className="btn btn-secondary btn-sm"
                        >
                          🤖 Ask AI Assistant for advice
                        </Link>
                      </div>
                    </div>
                  )}
                </div>
              );
            })
          ) : (
            <div className="card glass-panel p-8 text-center">
              <span style={{ fontSize: '2.5rem' }}>📭</span>
              <p className="body-sm text-secondary mt-2">No tasks found matching your filter selection.</p>
            </div>
          )}
        </div>
      </div>

      {/* Add Custom Task Modal */}
      {modalOpen && (
        <div className="modal-overlay">
          <div className="modal-content">
            <div className="modal-header">
              <h3 className="text-gold font-heading">Add Custom Task</h3>
              <button onClick={() => setModalOpen(false)} className="modal-close">×</button>
            </div>
            <form onSubmit={handleTaskSubmit}>
              <div className="modal-body">
                <div className="form-group">
                  <label className="form-label">Task Title</label>
                  <input 
                    type="text" 
                    required
                    placeholder="e.g. Choose groom shoes"
                    value={newTask.title}
                    onChange={(e) => setNewTask(prev => ({ ...prev, title: e.target.value }))}
                    className="form-input"
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">Category</label>
                  <select 
                    value={newTask.category}
                    onChange={(e) => setNewTask(prev => ({ ...prev, category: e.target.value }))}
                    className="form-select"
                  >
                    {['Planner', 'Venue', 'Catering', 'Photography', 'Videography', 'Florals', 'Music', 'Attire', 'Hair & Makeup', 'Invitations', 'Bakery', 'Rings', 'Decor', 'Misc'].map(cat => (
                      <option key={cat} value={cat}>{cat}</option>
                    ))}
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label">Due Date</label>
                  <input 
                    type="date" 
                    required
                    value={newTask.dueDate}
                    onChange={(e) => setNewTask(prev => ({ ...prev, dueDate: e.target.value }))}
                    className="form-input"
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">Assigned To</label>
                  <select 
                    value={newTask.assignedTo}
                    onChange={(e) => setNewTask(prev => ({ ...prev, assignedTo: e.target.value }))}
                    className="form-select"
                  >
                    <option value="Both">Both of us</option>
                    <option value="Bride">Bride</option>
                    <option value="Groom">Groom</option>
                    <option value="Planner">Planner Coordinator</option>
                  </select>
                </div>
                <div className="form-group">
                  <label className="form-label">Notes & Instructions</label>
                  <textarea 
                    placeholder="Provide details or constraints for this task..."
                    value={newTask.notes}
                    onChange={(e) => setNewTask(prev => ({ ...prev, notes: e.target.value }))}
                    className="form-textarea"
                  />
                </div>
              </div>
              <div className="modal-footer">
                <button type="button" onClick={() => setModalOpen(false)} className="btn btn-secondary btn-sm">Cancel</button>
                <button type="submit" className="btn btn-primary btn-sm">Create Task</button>
              </div>
            </form>
          </div>
        </div>
      )}

      <style jsx>{`
        .checklist-layout {
          background: transparent;
          color: #f5f0e8;
          min-height: 100vh;
        }
        .navbar-spacer {
          height: 80px;
        }
        .max-w-4xl {
          max-width: 56rem;
          margin: 0 auto;
        }
        .progress-bar-bg {
          height: 10px;
          background: rgba(255, 255, 255, 0.08);
          border-radius: 5px;
          overflow: hidden;
        }
        .progress-bar-fill {
          height: 100%;
          background: linear-gradient(90deg, #c9a96e 0%, #b8944f 100%);
          border-radius: 5px;
          transition: width 0.4s ease;
        }
        .bg-secondary {
          background: rgba(26, 26, 46, 0.5);
        }
        .bg-secondary-opaque {
          background: rgba(13, 13, 26, 0.4);
        }
        .border-divider {
          border-color: rgba(201, 169, 110, 0.1);
        }
        .tab.bg-gold {
          background: #c9a96e;
          color: #0d0d1a;
        }
        @media (max-width: 600px) {
          .tabs {
            overflow-x: auto;
            white-space: nowrap;
            display: flex;
            scrollbar-width: none;
          }
          .tabs::-webkit-scrollbar {
            display: none;
          }
          .tab {
            flex: 0 0 auto !important;
            padding: 10px 16px !important;
          }
        }
        .task-card-item {
          border-left: 3px solid #6366f1; /* base default */
          transition: all 0.3s ease;
        }
        .task-card-item:hover {
          transform: translateX(4px);
        }
        .task-completed-style {
          border-left-color: #4ade80 !important;
          opacity: 0.75;
        }
        .task-overdue-style {
          border-left-color: #ef4444 !important;
          background: radial-gradient(circle at left, rgba(239, 68, 68, 0.05) 0%, transparent 40%);
        }
        .task-checkbox {
          width: 20px;
          height: 20px;
          accent-color: #c9a96e;
          cursor: pointer;
        }
        .category-dot {
          display: inline-block;
          width: 8px;
          height: 8px;
          border-radius: 50%;
        }
        .task-notes-expanded {
          border-top: 1px solid rgba(201, 169, 110, 0.1);
        }
        .line-through {
          text-decoration: line-through;
        }
        .animate-pulse {
          animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
        }
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: .5; }
        }
        .mb-1 { margin-bottom: 4px; }
        .mb-2 { margin-bottom: 8px; }
        .mb-6 { margin-bottom: 24px; }
        .mt-1 { margin-top: 4px; }
        .mt-2 { margin-top: 8px; }
        .mt-4 { margin-top: 16px; }
        .py-8 { padding-top: 32px; padding-bottom: 32px; }
        .p-4 { padding: 16px; }
        .p-6 { padding: 24px; }
        .flex-col { display: flex; flex-direction: column; }
        .flex-between { display: flex; align-items: center; justify-content: space-between; }
        .flex-start { display: flex; align-items: center; justify-content: flex-start; }
        .flex-wrap { flex-wrap: wrap; }
        .gap-2 { gap: 8px; }
        .gap-3 { gap: 12px; }
        .gap-4 { gap: 16px; }
        .font-bold { font-weight: 700; }
        .w-full { width: 100%; }
        .ml-2 { margin-left: 8px; }
      `}</style>
    </main>
  );
}
